# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAppTypescript' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestAppTypescript
  pod 'AppCenter/Push', '~> 1.13.0'
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', :path => '../../AppCenterReactNativeShared/Products/'

  

  platform :ios, '9.0'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'TestAppTypescriptTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestAppTypescript-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestAppTypescript-tvOS

  target 'TestAppTypescript-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
